{
 "title": "0-HuaweiCloud Overview Dashboard-0428",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "接入层", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 } },
  { "title": "华为云集群资源层", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 6, "y": 0 } },
  { "title": "中间件层", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "4XX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(huaweicloud_sys_waf_waf_http_4xx{epId=\"9b108c79-9b8a-40fd-a506-a29ff285db1f\"}) by (epId)"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(huaweicloud_sys_waf_waf_http_5xx{epId=\"9b108c79-9b8a-40fd-a506-a29ff285db1f\"}) by (epId)"
    }
   ]
  },
  {
   "title": "集群资源使用量",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aom_cluster_cpu_usage{clusterName=\"lm-cce-turbo-new\"}) by (clusterId)",
     "legendFormat": "CPU（%）"
    },
    {
     "expr": "avg(aom_cluster_memory_usage{clusterName=\"lm-cce-turbo-new\"}) by (clusterId)",
     "legendFormat": "内存（%）"
    },
    {
     "expr": "avg(aom_cluster_disk_usage{clusterName=\"lm-cce-turbo-new\"}) by (clusterId)",
     "legendFormat": "磁盘（%）"
    }
   ]
  },
  {
   "title": "定时任务（XXL-JOB）",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select SUM(suc_count) suc_count,SUM(fail_count) fail_count from xxl_job_log_report where TO_DAYS(NOW()) - TO_DAYS(trigger_day) = 0"
    }
   ]
  },
  {
   "title": "MQ消息堆积量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_instance_accumulation",
     "legendFormat": "MQ消息堆积量"
    }
   ]
  },
  {
   "title": "Ingress-整体QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{}[2m]))",
     "legendFormat": "QPS"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{}[2m] offset 1d))",
     "legendFormat": "前1天QPS"
    }
   ]
  },
  {
   "title": "消息堆积（Group&Topic）TOP3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3,huaweicloud_sys_dms_group_topic_accumulation) ",
     "legendFormat": "{{reliablemq_groups}}"
    }
   ]
  },
  {
   "title": "产生死信消息的数量（Group&Topic）TOP3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3,rate(huaweicloud_sys_dms_dlq_accumulation{}[1d]))",
     "legendFormat": "{{reliablemq_dlq_topics}}"
    }
   ]
  },
  {
   "title": "Node数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster_name=\"lm-cce-turbo-new\",node!=\"virtual-kubelet\"}) by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Pod数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster_name=\"lm-cce-turbo-new\",created_by_kind!~\"<none>|Job\"} )by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "CPU超卖（倍）",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(allocatableCpuUsage{namespace=\"CCE.node_metric\",node_ip!=\"virtual-kubelet\"}) / count(allocatableCpuUsage{namespace=\"CCE.node_metric\",node_ip!=\"virtual-kubelet\"}) / 100",
     "legendFormat": "CPU分配率"
    }
   ]
  },
  {
   "title": "内存超卖（倍）",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(allocatableMemoryUsage{namespace=\"CCE.node_metric\",node_ip!=\"virtual-kubelet\"}) / count(allocatableMemoryUsage{namespace=\"CCE.node_metric\",node_ip!=\"virtual-kubelet\"}) / 100",
     "legendFormat": "内存分配率"
    }
   ]
  },
  {
   "title": "Apollo使用量",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aom_container_cpu_usage{clusterName=\"lm-cce-turbo-new\",nameSpace=\"hwy-apollo-config\",deploymentName=\"apollo-service-hwy-apollo-configservice\"}) by (deploymentName) ",
     "legendFormat": "CPU（%）"
    },
    {
     "expr": "avg(aom_container_memory_usage{clusterName=\"lm-cce-turbo-new\",nameSpace=\"hwy-apollo-config\",deploymentName=\"apollo-service-hwy-apollo-configservice\"}) by (deploymentName)",
     "legendFormat": "内存（%）"
    }
   ]
  },
  {
   "title": "NODE资源情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(aom_node_cpu_usage{clusterName=\"lm-cce-turbo-new\",master!=\"true\"}) by (hostName)",
     "legendFormat": "CPU使用率（%）"
    },
    {
     "expr": "avg(aom_node_memory_usage{clusterName=\"lm-cce-turbo-new\",master!=\"true\"}) by (hostName)",
     "legendFormat": "内存使用率（%）"
    },
    {
     "expr": "avg(aom_node_disk_usage{clusterName=\"lm-cce-turbo-new\",master!=\"true\"}) by (hostName)",
     "legendFormat": "磁盘使用率（%）"
    },
    {
     "expr": "aom_node_status{clusterName=\"lm-cce-turbo-new\",master!=\"true\"}",
     "legendFormat": "节点状态"
    }
   ]
  },
  {
   "title": "REDIS资源使用情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(huaweicloud_sys_dcs_cpu_usage{}) by (name) -0",
     "legendFormat": "CPU使用率（%）"
    },
    {
     "expr": "avg(huaweicloud_sys_dcs_memory_usage) by (name) -0",
     "legendFormat": "内存使用率（%）"
    },
    {
     "expr": "avg(huaweicloud_sys_dcs_bandwidth_usage) by (name) -0",
     "legendFormat": "带宽使用率（%）"
    },
    {
     "expr": "avg(huaweicloud_sys_dcs_rx_controlled) by (name) -0",
     "legendFormat": "流控次数"
    }
   ]
  },
  {
   "title": "命中率（%）-Bottom3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(3,huaweicloud_sys_dcs_keyspace_hits_perc{epId=\"9b108c79-9b8a-40fd-a506-a29ff285db1f\"}) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "响应时间（us）-TOP3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3,huaweicloud_sys_dcs_command_avg_rt{epId=~\"9b108c79-9b8a-40fd-a506-a29ff285db1f\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ingress总的请求成功率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"200\"}[2m])) / sum(rate(nginx_ingress_controller_requests{}[2m])) *100"
    }
   ]
  },
  {
   "title": "POD资源概览",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "avg(aom_container_cpu_usage{nameSpace!=\"kube-system\",nameSpace!=\"monitoring\",nameSpace!=\"hwtest-node-dx\",clusterName=\"lm-cce-turbo-new\"}) by (clusterName,nameSpace,deploymentName,podName)",
     "legendFormat": "CPU使用率（%）"
    },
    {
     "expr": "avg(aom_container_cpu_used_core{nameSpace!=\"kube-system\",nameSpace!=\"monitoring\",nameSpace!=\"hwtest-node-dx\",clusterName=\"lm-cce-turbo-new\"}) by (clusterName,nameSpace,deploymentName,podName)",
     "legendFormat": "CPU内核占用（Core）"
    },
    {
     "expr": "avg(aom_container_memory_usage{nameSpace!=\"kube-system\",nameSpace!=\"monitoring\",nameSpace!=\"hwtest-node-dx\",clusterName=\"lm-cce-turbo-new\"}) by (clusterName,nameSpace,deploymentName,podName)",
     "legendFormat": "内存使用率（%）"
    },
    {
     "expr": "avg(aom_container_memory_used_megabytes{nameSpace!=\"kube-system\",nameSpace!=\"monitoring\",nameSpace!=\"hwtest-node-dx\",clusterName=\"lm-cce-turbo-new\"}) by (clusterName,nameSpace,deploymentName,podName)",
     "legendFormat": "物理内存使用量"
    },
    {
     "expr": "avg(aom_container_network_receive_bytes{nameSpace!=\"kube-system\",nameSpace!=\"monitoring\",nameSpace!=\"hwtest-node-dx\",clusterName=\"lm-cce-turbo-new\"}) by (clusterName,nameSpace,deploymentName,podName)",
     "legendFormat": "下行Bps"
    },
    {
     "expr": "avg(aom_container_network_transmit_bytes{nameSpace!=\"kube-system\",nameSpace!=\"monitoring\",nameSpace!=\"hwtest-node-dx\",clusterName=\"lm-cce-turbo-new\"}) by (clusterName,nameSpace,deploymentName,podName)",
     "legendFormat": "上行Bps"
    }
   ]
  },
  {
   "title": "POD重启次数",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace!=\"kube-system\",cluster_name=\"lm-cce-turbo-new\"}) by (pod,namespace) >0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "数据库每秒慢查询数",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(huaweicloud_sys_gaussdb_gaussdb_mysql074_slow_queries{}) by (gaussdb_mysql_instance_id)",
     "legendFormat": "{{gaussdb_mysql_instance_id}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(huaweicloud_sys_gaussdb_gaussdb_mysql008_qps{}) by (gaussdb_mysql_instance_id) -0",
     "legendFormat": "{{gaussdb_mysql_instance_id}}"
    }
   ]
  },
  {
   "title": "SHENYU-整体QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(shenyu_request_total{}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GaussDB MySQL资源使用情况 ",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(huaweicloud_sys_gaussdb_gaussdb_mysql001_cpu_util{}) by (instanceName)",
     "legendFormat": "CPU使用率（%）"
    },
    {
     "expr": "avg(huaweicloud_sys_gaussdb_gaussdb_mysql002_mem_util{}) by (instanceName)",
     "legendFormat": "内存使用率（%）"
    },
    {
     "expr": "avg(huaweicloud_sys_gaussdb_gaussdb_mysql119_disk_used_ratio{}) by (instanceName)",
     "legendFormat": "磁盘使用率（%）"
    },
    {
     "expr": "avg(huaweicloud_sys_gaussdb_gaussdb_mysql072_conn_usage{}) by (instanceName)",
     "legendFormat": "连接数使用率（%）"
    }
   ]
  }
 ]
}